cc_library(
    name = "rehax-jsc",
    srcs = [
        "generated/rehax/binding.cpp",
    ],
    hdrs = [
        "generated/rehax/binding.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//native-abstraction:rehax-ui-appkit",
    ]
)